name: sdapp
description: A new Flutter project.

publish_to: "none" # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - "images/login_background.png"
    - "images/logo.png"
    - "images/login_text.png"
    - "images/signup_text.png"
  fonts:
  - family: Poppins
    fonts:
      - asset: assets/Poppins-Black.ttf
      - asset: assets/Poppins-Bold.ttf
        weight: 700

  
  